---
apache_enablerepo: ''

apache_listen_ip: '*'
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_keepalive: true
apache_keepalive_requests: 500
apache_keepalive_timeout: 5

apache_prefork_server_limit: 256
apache_prefork_start_servers: 5
apache_prefork_min_spare_servers: 5
apache_prefork_max_spare_servers: 10
apache_prefork_max_clients: 256
apache_prefork_max_requests_per_child: 0

apache_worker_server_limit: 16
apache_worker_start_servers: 3
apache_worker_min_spare_threads: 75
apache_worker_max_spare_threads: 250
apache_worker_max_clients: 400
apache_worker_max_requests_per_child: 0
apache_worker_thread_limit: 64
apache_worker_threads_per_child: 25

apache_event_server_limit: 16
apache_event_start_servers: 3
apache_event_min_spare_threads: 75
apache_event_max_spare_threads: 250
apache_event_max_clients: 400
apache_event_max_requests_per_child: 0
apache_event_thread_limit: 64
apache_event_threads_per_child: 25

apache_remove_default_aliases: True

apache_base_dir: '/var/www'
apache_web_subdir: 'web'
apache_ssl_subdir: 'ssl'
apache_private_subdir: 'private'

apache_create_vhosts: true
apache_vhosts_filename: 'vhosts.conf'

# On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
# Set this to `true` to remove that default.
apache_remove_default_vhost: false

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html index.htm

apache_global_vhost_access_log_format_combined: '%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"'
apache_global_vhost_access_log_format_proxy: '%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"'

apache_global_vhost_aliases: []
  # Available properties
  # - name: alias-url
  #   dest: alias-path

apache_global_vhost_custom_errors: []
  # Available properties
  # - code: error-code
  #   action: error-action

apache_vhosts:
  - servername: 'local.dev'
    documentroot: '/var/www/html'
  # Available properties
  # - servername: 'local.dev'
  #   serveralias:
  #     - 'alias1.local'
  #     - 'alias2.local'
  #   serveradmin: webmaster@localhost
  #   documentroot: '/var/www/html'
  #   separate_logs: true
  #   separate_logs_proxy_format: true
  #   custom_errors:
  #     - code: error-code
  #       action: error-action
  #   frame_options: SAMEORIGIN
  #   deflate: true
  #   deflate_dont_vary: User-Agent
  #   fileetag: true
  #   aliases:
  #     - name: alias-url
  #       dest: alias-path
  #   setenvif:
  #     - attribute: 'X-Forwarded-For'
  #       pattern: '(.*)'
  #       var: 'ENV_VAR'
  #       value: 'true'
  #   redirect_to_https: false
  #   allowoverride: 'All'
  #   rewritebase: '/'
  #   custom_rewrites:
  #     - pattern: regex
  #       substitution: text
  #       flags: '[R=301,L]'
  #       conditions:
  #         - test_string: '%{HTTP_HOST}'
  #           pattern: '^old\.site\.com$'
  #           flags: '[NC]'
  #   redirect_to_servername: True
  #   exclude_from_redirect:
  #     - 'valid.alias.com'
  #   redirect_to_file: '/index.php'
  #   restricted_access:
  #     - path: '/secret'
  #       regex: false
  #       all: false
  #       ips:
  #         - '127.0.0.1'
  #         - '192.168.0.1'
  #       hosts:
  #         - 'www.site.com'
  #       env_variables:
  #         - 'ENV_VAR'
  #       htpasswd: '/.htpasswd'
  #   extra_parameters: 'Custom VHost configuration'

apache_vhosts_ssl: []
  # Available properties
  # - servername: 'local.dev'
  #   serveralias:
  #     - 'alias1.local'
  #     - 'alias2.local'
  #   serveradmin: webmaster@localhost
  #   documentroot: '/var/www/html'
  #   certificate_file: '/path/to/certificate.crt'
  #   certificate_key_file: '/path/to/certificate.key'
  #   certificate_chain_file: '/path/to/certificate_chain.crt'
  #   sts: true
  #   sts_max_age: '63072000'
  #   sts_subdomains: true
  #   separate_logs: true
  #   separate_logs_proxy_format: true
  #   custom_errors:
  #     - code: error-code
  #       action: error-action
  #   frame_options: SAMEORIGIN
  #   deflate: true
  #   deflate_dont_vary: User-Agent
  #   fileetag: true
  #   aliases:
  #     - name: alias-url
  #       dest: alias-path
  #   setenvif:
  #     - attribute: 'X-Forwarded-For'
  #       pattern: '(.*)'
  #       var: 'ENV_VAR'
  #       value: 'true'
  #   redirect_to_http: false
  #   allowoverride: 'All'
  #   rewritebase: '/'
  #   custom_rewrites:
  #     - pattern: regex
  #       substitution: text
  #       flags: '[R=301,L]'
  #       conditions:
  #         - test_string: '%{HTTP_HOST}'
  #           pattern: '^old\.site\.com$'
  #           flags: '[NC]'
  #   redirect_to_servername: True
  #   exclude_from_redirect:
  #     - 'valid.alias.com'
  #   redirect_to_file: '/index.php'
  #   restricted_access:
  #     - path: '/secret'
  #       regex: false
  #       all: false
  #       ips:
  #         - '127.0.0.1'
  #         - '192.168.0.1'
  #       hosts:
  #         - 'www.site.com'
  #       env_variables:
  #         - 'ENV_VAR'
  #       htpasswd: '/.htpasswd'
  #   extra_parameters: 'Custom VHost configuration'

apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: 'All -SSLv2 -SSLv3'
apache_ssl_cipher_suite: 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH'

apache_frame_options: SAMEORIGIN

apache_sts: true
apache_sts_max_age: '63072000'
apache_sts_subdomains: true

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - headers.load
  - rewrite.load
  - socache_shmcb.load
  - ssl.conf
  - ssl.load
apache_mods_disabled: []

# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started
