---
apache_vhosts_version: '2.2'
apache_default_vhost_filename: 000-default
apache_ports_configuration_items:
  - regexp: '^Listen '
    line: 'Listen {{ apache_listen_port }}'
  - regexp: '^#?NameVirtualHost '
    line: 'NameVirtualHost {{ apache_listen_ip }}:{{ apache_listen_port }}'
apache_security_configuration_items:
  - regexp: '^TraceEnable '
    line: 'TraceEnable Off'
  - regexp: '^ServerSignature '
    line: 'ServerSignature Off'
  - regexp: '^ServerTokens '
    line: 'ServerTokens Prod'
apache_keepalive_configuration_items:
  - regexp: '^KeepAlive '
    line: 'KeepAlive {% if apache_keepalive %}On{% else %}Off{% endif %}'
  - regexp: '^MaxKeepAliveRequests '
    line: 'MaxKeepAliveRequests {{ apache_keepalive_requests }}'
  - regexp: '^KeepAliveTimeout '
    line: 'KeepAliveTimeout {{ apache_keepalive_timeout }}'
apache_mpm_prefork_configuration_items:
  - regexp: '^([ \t]*)StartServers(.*)$'
    line: '\1StartServers {{ apache_prefork_start_servers }}'
  - regexp: '^([ \t]*)MinSpareServers(.*)$'
    line: '\1MinSpareServers {{ apache_prefork_min_spare_servers }}'
  - regexp: '^([ \t]*)MaxSpareServers(.*)$'
    line: '\1MaxSpareServers {{ apache_prefork_max_spare_servers }}'
  - regexp: '^([ \t]*)MaxClients(.*)$'
    line: '\1MaxClients {{ apache_prefork_max_clients }}'
  - regexp: '^([ \t]*)MaxRequestsPerChild(.*)$'
    line: '\1MaxRequestsPerChild {{ apache_prefork_max_requests_per_child }}'
  - regexp: '^([ \t]*)ServerLimit[ \t]'
    line: 'ServerLimit {{ apache_prefork_server_limit }}'
    insertbefore: '^([ \t]*)MaxClients[ \t]'
apache_mpm_worker_configuration_items:
  - regexp: '^([ \t]*)StartServers(.*)$'
    line: '\1StartServers {{ apache_worker_start_servers }}'
  - regexp: '^([ \t]*)MinSpareThreads(.*)$'
    line: '\1MinSpareThreads {{ apache_worker_min_spare_threads }}'
  - regexp: '^([ \t]*)MaxSpareThreads(.*)$'
    line: '\1MaxSpareThreads {{ apache_worker_max_spare_threads }}'
  - regexp: '^([ \t]*)MaxClients(.*)$'
    line: '\1MaxClients {{ apache_worker_max_clients }}'
  - regexp: '^([ \t]*)MaxRequestsPerChild(.*)$'
    line: '\1MaxRequestsPerChild {{ apache_worker_max_requests_per_child }}'
  - regexp: '^([ \t]*)ThreadsPerChild(.*)$'
    line: '\1ThreadsPerChild {{ apache_worker_threads_per_child }}'
  - regexp: '^([ \t]*)ServerLimit[ \t]'
    line: 'ServerLimit {{ apache_worker_server_limit }}'
    insertbefore: '^([ \t]*)MaxClients[ \t]'
  - regexp: '^([ \t]*)ThreadLimit[ \t]'
    line: 'ThreadLimit {{ apache_worker_thread_limit }}'
    insertbefore: '^([ \t]*)ThreadsPerChild[ \t]'
apache_mpm_event_configuration_items:
  - regexp: '^([ \t]*)StartServers(.*)$'
    line: '\1StartServers {{ apache_event_start_servers }}'
  - regexp: '^([ \t]*)MinSpareThreads(.*)$'
    line: '\1MinSpareThreads {{ apache_event_min_spare_threads }}'
  - regexp: '^([ \t]*)MaxSpareThreads(.*)$'
    line: '\1MaxSpareThreads {{ apache_event_max_spare_threads }}'
  - regexp: '^([ \t]*)MaxClients(.*)$'
    line: '\1MaxClients {{ apache_event_max_clients }}'
  - regexp: '^([ \t]*)MaxRequestsPerChild(.*)$'
    line: '\1MaxRequestsPerChild {{ apache_event_max_requests_per_child }}'
  - regexp: '^([ \t]*)ThreadsPerChild(.*)$'
    line: '\1ThreadsPerChild {{ apache_event_threads_per_child }}'
  - regexp: '^([ \t]*)ServerLimit[ \t]'
    line: 'ServerLimit {{ apache_event_server_limit }}'
    insertbefore: '^([ \t]*)MaxClients[ \t]'
  - regexp: '^([ \t]*)ThreadLimit[ \t]'
    line: 'ThreadLimit {{ apache_event_thread_limit }}'
    insertbefore: '^([ \t]*)ThreadsPerChild[ \t]'
apache_alias_configuration_commented_items:
  - regexp: '^([ \t]+)Alias([ \t]+)\/icons\/([ \t])'
    line: '#\1Alias\2/icons/\3'
