---
- name: Create sites-available directory
  file:
    dest: "{{ apache_server_root }}/sites-available"
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: apache_create_vhosts

- name: Create sites-enabled directory
  file:
    dest: "{{ apache_server_root }}/sites-enabled"
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: apache_create_vhosts

