---
- include: define-variables.yml
- include: setup.yml
- include: apache-version.yml
- include: configure.yml

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes
